# Generated by Django 4.2.23 on 2025-12-16 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9]+$",
                        "Username must contain only lowercase letters and numbers",
                    )
                ],
            ),
        ),
    ]
