# Generated by Django 4.2.23 on 2025-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="eligibility",
            field=models.CharField(
                choices=[
                    ("eligible", "Eligible"),
                    ("not_eligible", "Not Eligible"),
                    ("pending_review", "Pending Review"),
                ],
                default="pending_review",
                max_length=15,
            ),
        ),
    ]
