# Generated by Django 4.2.23 on 2025-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_user_eligibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
