# Generated by Django 4.2.23 on 2025-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="basic",
                max_length=15,
            ),
        ),
    ]
