# Generated by Django 4.2.23 on 2025-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
