# Generated by Django 4.2.23 on 2025-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
